### ISSUE TITLE
Templates issue

### ISSUE THREAD

**Issue by crabbly** [sgsoft-studio/webed#1]
Right after installation, the themes won't work for me. I haven't really tried to do anything other than the basic install. Just thought that I should point this out. I'm attaching an image to show how my pages look like.
When it comes to the admin interface though, amazing job.  Works great. Thank you.
<img width="1017" alt="webdev page" src="https://cloud.githubusercontent.com/assets/16927940/20467879/b5372468-af5d-11e6-8b5d-a1b5b22a0ac4.png">

**Comment by duysolo** [comment]
Ok. Just go to Themes and **Install** your theme. If you just enable, the assets will not be publish to **public**.

Thanks.

**Comment by duysolo** [comment]
Then you need to set the template of that page to **Landing Page**.
Go to **Pages** --> select your page --> set the template in right corner.

**Comment by duysolo** [comment]
And please make sure that you have selected your page as default homepage. Check it at **Configuration** --> **Settings** --> **Theme options**

**Comment by crabbly** [comment]
Yea, I had selected the default homepage, however, I didn't install the theme dependencies. My bad. Thanks for pointing it out. I got to still go over the code itself. Just testing its basic installation flow. Works great. Thanks again.
