### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by monteiroands** [sgsoft-studio/webed#10]
After installing I got error 500

**Comment by duysolo** [comment]
Could you show me the error message?

**Comment by sangnguyenplus** [comment]
You need to chmod 777 for /bootstrap and /storage folders.

**Comment by duysolo** [comment]
I don't think so. I will check this issue.

**Comment by duysolo** [comment]
Everything still fine now. Could you describe the details when you see this bug?

**Comment by monteiroands** [comment]
That's exactly what the @sangnguyenplus commented, had to give permission 777 in the folders. Thanks guys for the force! :)
