### ISSUE TITLE
Most of the front end methods are not working in laravel 5.4 (WebEd 3.0) 

### ISSUE THREAD

**Issue by ishansd94** [sgsoft-studio/webed#13]
Hi,

I recently tried installing webed v3.0.9 with blog,custom-fields plugin and i created a bare theme.

most of the functions are missing eg: whereBelongsToTags in tags.php

**Comment by duysolo** [comment]
Hello,

I see. I'm refactoring these plugins, so maybe some methods are missing. This week everything will stable.
