### ISSUE TITLE
No hint path defined for [webbed-theme] 

### ISSUE THREAD

**Issue by nouphaltklm** [sgsoft-studio/webed#14]
The cms is not working

**Comment by duysolo** [comment]
Hello,

How can you see this bug?

**Comment by nouphaltklm** [comment]
after all the installation when we go to the admin url its showing **No hint path defined for [webbed-theme]**

**Comment by duysolo** [comment]
Hmmm. I'm already try to install it again and no problem happened.

I prefer you to install WebEd using

```
composer create-project --prefer-dist sgsoft-studio/webed webed
```

Could you show me the error screen?

**Comment by nikhil167** [comment]
Same problem for me >here is the error screen of admin panel
![untitled-1](https://cloud.githubusercontent.com/assets/26650913/24849811/1307bafc-1deb-11e7-9109-60b09b898ab3.jpg)

This is the Home page saying "You need to active a theme"
![2](https://cloud.githubusercontent.com/assets/26650913/24849842/3758f57e-1deb-11e7-90ce-3321abaa84df.jpg)

I am setting it on localhost using wamp
Thanks,

**Comment by duysolo** [comment]
Hello,
I didn't fix the app when using folder. You should  try the domain name, such as
```
http://webed.dev/
```
or run
```
php artisan serve
```
I'm fixing it.

**Comment by nikhil167** [comment]
I tried it by using "Add a Virtual Host" option in wamp, but not worked.
Hope you will fix it soon
Thanks.

**Comment by nikhil167** [comment]
I just installed the 3.0 version of webed so i can run plugins right?
i did that and now i can't activate the theme >no errors are showing
![4](https://cloud.githubusercontent.com/assets/26650913/24897460/9b8b198e-1eb6-11e7-8aac-668fbe38a148.jpg)

what i did wrong?
Please help. I'm a beginner 
Thanks

**Comment by duysolo** [comment]
Hello,

Maybe your system does not allow run composer dump-autoload automatically.
You can run `composer dump-autoload` by yourself.

**Comment by nikhil167** [comment]
Thanks for responding,
I tried it , not working. I clicked the 'active ' button then 'active this theme' ok and this alert box with"composer autoload refreshed" pops up.
I think i made a mistake somewhere, How can i check i installed it correctly.
Thanks

**Comment by duysolo** [comment]
Ok I see. 
You can check them in `composer.json`, `autoload psr-4` section.
Could you write the autoload psr-4 section in that file to here?

**Comment by nikhil167** [comment]
"autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "WebEd\\Plugins\\CustomFields\\": "C:\\wamp64\\www\\webedcms\\plugins\\custom-fields-master/src",
            "WebEd\\Themes\\Sedna\\": "C:\\wamp64\\www\\webedcms\\themes\\sedna-master/src"
        }
    },

This is what it looks like

**Comment by nikhil167** [comment]
autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/",
            "WebEd\\Plugins\\CustomFields\\": "plugins/custom-fields/src",
            "WebEd\\Themes\\Sedna\\": "themes/sedna/src"
        }
    },
This is the composer.json from sample-data i think i did'nt replaced it .

now i got this in both composer.json file one inside the theme folder one outside and when i logged in
this shows
"The base module of this class is enabled, but class not found: WebEd\Plugins\CustomFields\Providers\ModuleProvider. Please review and add the namespace of this module to composer autoload section, then run composer dump-autoload"

Sorry for making this complicated :)

**Comment by duysolo** [comment]
Yes. I think this system have some trouble on Windows. It throws a wrong dependencies path. I will check it.

For now, try to remove `C:\wamp64\www\webedcms\` in the path.

**Comment by nikhil167** [comment]
C:\wamp64\www\webedcms\
It keeps coming back after reloading. But all other errors are gone. Just the theme is not loading.
Could you please Install this on windows by using wamp.
Thanks, Looking forward for your reply :)

**Comment by ghost** [comment]
![front end error](https://cloud.githubusercontent.com/assets/19275984/24936634/7b6dc474-1f5d-11e7-9f6e-a0e3ae6f10bb.png)
![themes error](https://cloud.githubusercontent.com/assets/19275984/24936639/8665f52c-1f5d-11e7-9250-162fa6b9d100.png)

what i did wrong?
Please help. I'm a beginner
Thanks

**Comment by duysolo** [comment]
Which version of WebEd that you're using?

**Comment by ghost** [comment]
![webed ver](https://cloud.githubusercontent.com/assets/19275984/24938107/c89f5c26-1f67-11e7-894d-1d3b48e3bc02.png)

**Comment by duysolo** [comment]
That theme not working on v3.1. You can use the version 3.0 instead.

Btw, I'm fixing the plugins and make a default theme.

**Comment by ghost** [comment]
thank you

**Comment by nikhil167** [comment]
Hey, 
I installed the new released Version 3.1.9 that comes with a default theme but while Activating it
"Missing required module: webed-contact-form
Missing required module: webed-captcha"
What's the Problem here?


![167](https://cloud.githubusercontent.com/assets/26650913/25215462/5267ae82-25bb-11e7-9288-5b25a03eb607.jpg)

**Comment by duysolo** [comment]
:D sorry, I didn't update the plugins list.
You can go here to download these plugin:
`https://github.com/webed-plugins/contact-form`
`https://github.com/webed-plugins/captcha`

**Comment by nikhil167** [comment]
Yep Thanks. Now i installed the plugins and theme and the home page >

![167a](https://cloud.githubusercontent.com/assets/26650913/25217568/099d6462-25c5-11e7-8948-539727b71eb2.jpg)

And after i created a homepage >

![167b](https://cloud.githubusercontent.com/assets/26650913/25217614/353a45d6-25c5-11e7-9e2b-c25f20b5fafe.jpg)

:( Help

**Comment by duysolo** [comment]
No no no,
You need to read the `README.md` file in root of that theme.

**Comment by nikhil167** [comment]
Sorry Boss :P
My Mistake, Theme is Perfectly working.

**Comment by duysolo** [comment]
But it's not done yet. I'm will release soon.

**Comment by nikhil167** [comment]
Alright we are waiting.

**Comment by CHome92** [comment]
![aadmin](https://user-images.githubusercontent.com/31442180/29971113-725e371c-8f27-11e7-8039-80f003c83207.jpg)
He will not accept the password, but will not enter the password
