### ISSUE TITLE
how to install theme

### ISSUE THREAD

**Issue by khyoz** [sgsoft-studio/webed#15]
This project looks great ! Wanted to test it, but I have some problems to activate a theme, as it seems to be blank theme after installation.
My font page and backend page are white. I have downloaded Sedna theme, but cannot activate it, when I go to the plugins page, the list is empty. no idea about how to do. Documentation is not very explicit, I have difficulties to understand if we need to unzip theme, or just copy it....
![2017-03-29 14_16_23-plugins _ webed](https://cloud.githubusercontent.com/assets/26684951/24454023/66fbbc7c-148a-11e7-8bce-33a8051d3761.png)

**Comment by duysolo** [comment]
Sorry, you need to setup virtual host, or run app using 
```
php artisan serve
```

**Comment by duysolo** [comment]
Btw, I'm working on WebEd 3.1. Coming asap.

**Comment by khyoz** [comment]
Nice to hear version 3.1 will come soon....but if you check the screenshot, you can see that I use a local server...and the screen is white. But, I will restart an installation in the next days from zero...maybe I forgot something...neverming, demo is nice and work is amazing ! tks to share !

**Comment by duysolo** [comment]
Hello,

Virtual host means the domain name, do not use folder.
Everything will be ok if you use as
```http://webed.dev/admincp...```

**Comment by duysolo** [comment]
And, I will fix the folder domain as you use before too.

**Comment by khyoz** [comment]
ok....I got it with php artisan serve....

![2017-03-29 14_38_32-dashboard _ webed 2](https://cloud.githubusercontent.com/assets/26684951/24454823/a49394e4-148d-11e7-95ed-5590c121b9f8.png)
Super cool ! As I always work with a local server, I don't really oftern use php artisan serve....
Your next fix will be cool....at least for me ! Thanks a lot !

**Comment by duysolo** [comment]
Ok, nice to help you. If you have some questions, feel free to contact me.
