### ISSUE TITLE
 Class 'WebEd\Base\Core\Providers\ModuleProvider' not found

### ISSUE THREAD

**Issue by tvad911** [sgsoft-studio/webed#16]
After run command : "composer create-project --prefer-dist sgsoft-studio/webed webed.dev"
I get an errror,   Class 'WebEd\Base\Core\Providers\ModuleProvider' not found on config/app.php.

After that i just check, vendor/sgsoft-studio/base/src/Providers/ModuleProvider.php,
 it's not in namespace:"WebEd\Base\Core\Providers". And i use WebEd\Base\Providers\ModuleProvider::class in app.php config but it's not work.

Please check again.

**Comment by duysolo** [comment]
Hello,

Please change 
`WebEd\Base\Core\Providers\ModuleProvider`
to
`WebEd\Base\Providers\ModuleProvider`
I'm updating docs
