### ISSUE TITLE
BadMethodCallException in Validator.php line 1067: Method [validateNulable] does not exist.

### ISSUE THREAD

**Issue by khyoz** [sgsoft-studio/webed#17]
In your online demo (users / edit user demo id = 3)
http://webed.hitbui.com/admincp/users/edit/3
I try to change the about field with a value and save...then I catch this error !
![2017-04-04 09_01_20-webed hitbui com_admincp_users_edit_3](https://cloud.githubusercontent.com/assets/26684951/24644722/5bc05f18-1915-11e7-8f98-8d0d2ebbb093.png)

**Comment by duysolo** [comment]
Hello,

I'm checking it.

**Comment by duysolo** [comment]
Move to new demo site
