### ISSUE TITLE
Error when run "php artisan cms:install"

### ISSUE THREAD

**Issue by tvad911** [sgsoft-studio/webed#18]
After run command i get an error.
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "cms" namespace.

When run : php artisan, i can find "cms" command.

I check in vendor/sgsoft-studio/base/src/Console/Commands/InstallCmsCommand.php and vendor/sgsoft-studio/base/src/Console/Commands/InstallCmsCommand/ConsoleServiceProvider.php

It's right but not work, please check.

**Comment by duysolo** [comment]
Did you require the 
`WebEd\Base\Providers\ModuleProvider::class` to `config/app.php`?

**Comment by tvad911** [comment]
`Did you require the
WebEd\Base\Providers\ModuleProvider::class to config/app.php?`

Yes, i add Did you require the
WebEd\Base\Providers\ModuleProvider::class to config/app.php. 

But it's not work. 
I think when you fix WebEd\Base\Core\Providers\ModuleProvider::class to WebEd\Base\Providers\ModuleProvider::class have something not true... Or something change in 5.4 when register command in vendor.

**Comment by duysolo** [comment]
This change just only effect on v3.1. I've test so many times, and it still works fine.
You might need to remove the vendor folder, then run
```
composer clear-cache
composer update
```

**Comment by tvad911** [comment]
Ok, now... it's work... Thanks for your help..
