### ISSUE TITLE
custom-fields - error

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#19]
http://webed/admincp/custom-fields

FatalErrorException in CustomFieldController.php line 12:
Class 'WebEd\Base\Core\Http\Controllers\BaseAdminController' not found

**Comment by duysolo** [comment]
Hello,

I'm doing to make all plugins work with WebEd 3.1. Everything will stable this week.

**Comment by yuri25** [comment]
Thank you very much, we are waiting. And please make a clean default template.

**Comment by yuri25** [comment]
php artisan theme: create myclean

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "theme:" is ambiguous (theme:create, theme:make:controller and 18 more).

**Comment by duysolo** [comment]
Yes, I will do it, of course :D

**Comment by jolusadev** [comment]
I am waiting too.

**Comment by duysolo** [comment]
The plugin *Custom Fields* has been moved to core. We dont need to download this plugin.
I'm making the blog work with this plugin.
