### ISSUE TITLE
Error when change admin route

### ISSUE THREAD

**Issue by sangnguyenplus** [sgsoft-studio/webed#2]
Hi,
I changed WEBED_ADMIN_ROUTE from admincp to admin. Then when access to /admin, I got error 404.

Go to /admincp got this error.
http://prntscr.com/dbi3cm

Please check it. Thanks!

**Comment by duysolo** [comment]
This error because of the plugin **Pages** is enabled but is not installed via composer. Please follow these steps:
- Login to dashboard
- Go to plugins --> Uninstall --> Disable the **Pages** plugin
- Try to enable and install it again!
