### ISSUE TITLE
Error "You need to active a theme" on install with active themes

### ISSUE THREAD

**Issue by densonclan** [sgsoft-studio/webed#20]
After following install instructions and having a theme active in the backend, I get the error

   You need to active a theme

**Comment by duysolo** [comment]
Which theme are you using?

**Comment by densonclan** [comment]
It had triangle when installed. Also tried adding sedna

**Comment by duysolo** [comment]
Sedna theme has been deprecated on WebEd 3.1.
Btw, did you follow the guide I put in `readme.md` file of triangle theme?

**Comment by tnvhung** [comment]
same issue: You need to active a theme
using triangle default theme, run composer dump-autoload but still not working
