### ISSUE TITLE
Unable to activate the default theme

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#21]
Does not work:(

Missing required module: webed-contact-form
Missing required module: webed-captcha

**Comment by duysolo** [comment]
Hello,

Download these modules here: 
[https://github.com/webed-plugins/contact-form](https://github.com/webed-plugins/contact-form)
[https://github.com/webed-plugins/captcha](https://github.com/webed-plugins/captcha)

**Comment by yuri25** [comment]
Ok, plugins installed. But now that's what:
yuran@REANIMATOR c:\OpenServer\domains\webed
$ php artisan vendor:publish --tag=webed-public-assets --force
Can't locate path: <C:\OpenServer\domains\webed\vendor\sgsoft-studio\modules-management\src\Providers/../../resources/themes>
Copied Directory [\vendor\sgsoft-studio\assets-management\resources\public] To [\public]
Copied Directory [\vendor\sgsoft-studio\elfinder\resources\public] To [\public]
Copied Directory [\vendor\sgsoft-studio\menu\resources\public] To [\public]
Copied Directory [\vendor\sgsoft-studio\users\resources\public] To [\public]
Copied Directory [\vendor\sgsoft-studio\custom-fields\resources\public] To [\public]
Can't locate path: <C:\OpenServer\domains\webed\vendor\sgsoft-studio\static-blocks\src\Providers/../../resources/public>
Copied Directory [\vendor\sgsoft-studio\base\resources\root] To []
Copied Directory [\vendor\sgsoft-studio\base\resources\public] To [\public]
Can't locate path: <C:\OpenServer\domains\webed\plugins\blocks\src\Providers/../../resources/public>
Can't locate path: <C:\OpenServer\domains\webed\plugins\blog\src\Providers/../../resources/public>
Can't locate path: <C:\OpenServer\domains\webed\plugins\contact-form\src\Providers/../../resources/public> Copied Directory [\plugins\ide\resources\public] To [\public]
Copied Directory [\themes\triangle\resources\public] To [\public]
Publishing complete.

**Comment by yuri25** [comment]
On the main page is ....

ErrorException in UrlGenerator.php line 304:
Route [front.search.get] not defined. (View: C:\OpenServer\domains\webed\themes\triangle\resources\views\front\_partials\header.blade.php) (View: C:\OpenServer\domains\webed\themes\triangle\resources\views\front\_partials\header.blade.php) (View: C:\OpenServer\domains\webed\themes\triangle\resources\views\front\_partials\header.blade.php)

ErrorException in UrlGenerator.php line 304:
Route [front.search.get] not defined. (View: C:\OpenServer\domains\webed\themes\triangle\resources\views\front\_partials\header.blade.php) (View: C:\OpenServer\domains\webed\themes\triangle\resources\views\front\_partials\header.blade.php)


ErrorException in UrlGenerator.php line 304:
Route [front.search.get] not defined. (View: C:\OpenServer\domains\webed\themes\triangle\resources\views\front\_partials\header.blade.php)


InvalidArgumentException in UrlGenerator.php line 304:
Route [front.search.get] not defined.

**Comment by duysolo** [comment]
Hello,
In folder `themes/triangle/sample-data/config` you will have the config files. Please copy them to /config of your app.

**Comment by duysolo** [comment]
Btw, please follow the `readme.md` file in the triangle theme folder.

**Comment by yuri25** [comment]
Oh it turned out! thank you very much!

**Comment by duysolo** [comment]
Ok.
