### ISSUE TITLE
How to reset the admin password?

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#22]
For some reason, access to the admin panel has stopped ...
Sign in to start your session
These credentials do not match our records!!!

Login and password I did not change
During the installation I set such:
admin
password
Why does not it work now :(

**Comment by duysolo** [comment]
Hello,
You can reset password by eloquent:
```
User::find(69)->update(['password' => '123456']);
```
You don't need to bcrypt the password before save, because system will do it automatically.
