### ISSUE TITLE
When installed on a hosting server, it generates such errors

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#23]
# php artisan vendor:publish --tag=webed-public-assets --force
Can't locate path: </........./ptznew.ru/vendor/sgsoft-studio/modules-management/src/Providers/../../resources/themes>
Copied Directory [/vendor/sgsoft-studio/assets-management/resources/public] To [/public]
Copied Directory [/vendor/sgsoft-studio/elfinder/resources/public] To [/public]
Copied Directory [/vendor/sgsoft-studio/menu/resources/public] To [/public]
Copied Directory [/vendor/sgsoft-studio/users/resources/public] To [/public]
Copied Directory [/vendor/sgsoft-studio/custom-fields/resources/public] To [/public]
Can't locate path: </......../ptznew.ru/vendor/sgsoft-studio/static-blocks/src/Providers/../../resources/public>
Copied Directory [/vendor/sgsoft-studio/base/resources/root] To []
Copied Directory [/vendor/sgsoft-studio/base/resources/public] To [/public]
Copied Directory [/themes/triangle/resources/public] To [/public]
Publishing complete.

**Comment by duysolo** [comment]
Hello,

It's because of I defined the publish directory, but nothing in those folders.
It's not bugs, you can ignore it.

**Comment by yuri25** [comment]
All the same does not work .... That one that another ... Not all plugins are correctly activated .... The theme also is not activated ...

**Comment by yuri25** [comment]
FatalErrorException in AbstractController.php line 33:
Call to undefined function WebEd\Themes\Triangle\Http\Controllers\google_recaptcha()

**Comment by duysolo** [comment]
Hello,

I will remove the contact form on triangle theme.

**Comment by yuri25** [comment]
Look, please .... layout does not work at all

http://ptznew.ru/

**Comment by yuri25** [comment]
Plugin Custom fields not activated...

**Comment by duysolo** [comment]
Hello,
You dont need to install plugin custom fields, because it's moved to core

**Comment by yuri25** [comment]
Ok, I'll try to reinstall everything. From plug-ins install only the form of contacts and captcha? Or some other plug-ins you need to install?

**Comment by yuri25** [comment]
Something that already turns out, thank you very much for your help and answers.

**Comment by yuri25** [comment]
It's much better now :)    http://ptznew.ru
Tell me please to change the contents of footer which rights to what folders and files need to be set? In the admin panel, I change this data FOOTER CUSTOM FIELDS - Client name for example to Yuran Rea - the data is not saved. All the same remains Tedozi Manson. Also add add testimonial - fill in the field data - nothing stores either the data or the field itself. Please help me.

**Comment by yuri25** [comment]
Still such question how to make comments to posts by default on English, and that now only Vietnamese language. Tell me please.

**Comment by duysolo** [comment]
Hello,
You mean the facebook comments, right?

**Comment by duysolo** [comment]
And could you please send me the credentials to login to your system?

**Comment by yuri25** [comment]
Login to adminpanel:
admin
sp-981195
This is a test site http://ptznew.ru

**Comment by yuri25** [comment]
Or do you need ftp access to the server?

**Comment by yuri25** [comment]
What has become clearer on the above problems?

**Comment by duysolo** [comment]
Hello,

Could you explain the issue again?

**Comment by yuri25** [comment]
Tell me please to change the contents of footer which rights to what folders and files need to be set? In the admin panel, I change this data FOOTER CUSTOM FIELDS - Client name for example to Yuran Rea - the data is not saved. All the same remains Tedozi Manson. Also add add testimonial - fill in the field data - nothing stores either the data or the field itself. Please help me.

**Comment by yuri25** [comment]
Login to admin. 
http://ptznew.ru/admincp/pages/edit/1

Change the field and picture values. Then save the page. When you go to the home page you can see that nothing has changed.
The same applies to the Footer custom fields page

**Comment by duysolo** [comment]
I'm checking the reason why.

**Comment by duysolo** [comment]
I think it has some error on the javascript file of custom fields. I'm checking it.

**Comment by duysolo** [comment]
Hello,
It's because of the plugin **Blog** overwrite the custom fields hook of pages.
You need to download the latest blog plugin to fix it.
Please go here: [https://github.com/webed-plugins/blog](https://github.com/webed-plugins/blog)

**Comment by yuri25** [comment]
Thank you very much. Now I'll check it out. The result will be reported here.

**Comment by yuri25** [comment]
Thank you very much. This problem is solved, the results of the check can be viewed on the same site   http://ptznew.ru
Once again a huge thanks!

**Comment by duysolo** [comment]
I'm so happy that could help you.
