### ISSUE TITLE
cho mình hỏi xíu ạ

### ISSUE THREAD

**Issue by rin1906** [sgsoft-studio/webed#24]
Mình là một newbie lần đầu install laravel 5.4 này. Bạn có thể hướng dẫn cho mình được không ạ. Mình cảm ơn bạn nhiều. Mình có thử install rồi mà ko được bạn à

**Comment by duysolo** [comment]
Hello Rin,

Bạn đọc kỹ phần documentation nhe. 
Hoặc bạn truy cập link này để đọc documentation 
[https://webed.sgsoft-studio.com/docs/3.1/installation](https://webed.sgsoft-studio.com/docs/3.1/installation)

**Comment by rin1906** [comment]
phần install này sẽ download toàn bộ code mới của laravel về và nằm trong phần webeb đúng không ạ.

**Comment by duysolo** [comment]
Đúng rồi bạn.
Toàn bộ dependencies sẽ được composer download về giúp bạn :)

**Comment by rin1906** [comment]
http://imgur.com/a/Lk9zT

Mình install xong rồi ạ.
Mình chạy domain như trên thì không được. 
Vậy là sao nhĩ. Bạn giúp mình với.
Đây là lần đầu mình settup Laravel ^^

**Comment by duysolo** [comment]
Mình nghĩ bạn nên kiểm tra lại xampp của bạn.

**Comment by rin1906** [comment]
mình mới tải bản xampp 3.2.2 lúc sáng nay và install. Cũng để mình thử cài đặt lại xem thế nào. cảm ơn bạn đã trả lời nhiệt tình ^^

**Comment by duysolo** [comment]
Xampp bạn trả về 404. Điều này đúng, do source code Laravel chạy từ folder public chứ k phải folder gốc.
Cách giải quyết thì có 2 cách:
- Run `php artisan serve`.
- Run bằng đường link: `localhost/webed/public/admincp`.

**Comment by rin1906** [comment]
Missing required module: webed-custom-fields 
mình active theme thì bị báo lỗi như này bạn ạ

**Comment by duysolo** [comment]
Theme Sedna đã bị bỏ. Bạn xài theme default đi.

**Comment by rin1906** [comment]
bạn hướng dẫn mình install theme được không. mình chưa biết cài ^^
