### ISSUE TITLE
migrations

### ISSUE THREAD

**Issue by bensialih** [sgsoft-studio/webed#25]
Issue running migration on postgres

getting the following error

SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "MODIFY"
LINE 1: ALTER TABLE theme_options MODIFY value TEXT NULL

I recommend you remove the alter statements
DB::statement('ALTER TABLE theme_options MODIFY value TEXT NULL');
in file
set_theme_option_nullable

seems ok after that
will fork repo then resubmit

Thanks

**Comment by duysolo** [comment]
Ok I see,
I did not use Postgres SQL yet.

I will use `doctrine/dbal` to modify columns instead of raw SQL.

**Comment by duysolo** [comment]
Used `doctrine/dbal` to modify columns instead of raw SQL.
