### ISSUE TITLE
ErrorException in UrlGenerator.php line 304

### ISSUE THREAD

**Issue by yabasha** [sgsoft-studio/webed#26]
After installing the cms, enable theme, install theme make one page default page from setting configurations, I got the subjected exception.
<img width="765" alt="exception" src="https://cloud.githubusercontent.com/assets/932321/25989428/c26a18a0-3704-11e7-8ad8-fdaca13cf48c.png">

Why you don't provide a clean stable version and installation guide for the cms?

**Comment by duysolo** [comment]
Hello,

I'm fixing it.

**Comment by duysolo** [comment]
Fixed.
Please run these command:
```
composer update
php artisan vendor:publish --provider=WebEd\Base\Providers\ModuleProvider --tag=webed-assets --force
```

**Comment by chandnitin333** [comment]
php artisan vendor:publish --provider=WebEd\Base\Providers\ModuleProvider --tag=webed-assets --force 
not work 
nothing to publish for tag [webed-assets]
