### ISSUE TITLE
php artisan command return rutime error

### ISSUE THREAD

**Issue by tlamhuynh** [sgsoft-studio/webed#27]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__constru
  ct() must be an instance of Illuminate\Http\Request, null given, called in
 *\vendor\laravel\framework\src\Illuminate\Routing\Routi
  ngServiceProvider.php on line 64

**Comment by duysolo** [comment]
Hello,

I'm fixing it.

**Comment by duysolo** [comment]
Could you please check this issue again?
