### ISSUE TITLE
Table Plugin doesnt exsit issue

### ISSUE THREAD

**Issue by goodman77** [sgsoft-studio/webed#29]
I followed these instructions to install the CMS intop of an exsisting Laravel 5.4 project I have:

"sgsoft-studio/base": "3.1.*"
 
Then please register the WebEd provider to config/app.php
 
WebEd\Base\Providers\ModuleProvider::class.
 
Then create the folder plugins, themes in root folder of your application.

when I go to / , I am getting an error : 
**SQLSTATE[42S02]: Base table or view not found: 1146 Table 'plugins' doesn't exist**

**Comment by duysolo** [comment]
Did you try to run 
```
php artisan cms:install
```

**Comment by goodman77** [comment]
I will try to run it now and see

**Comment by goodman77** [comment]
Just ran it , and it gave me errors : Base table or view already exists: 1050 Table 'users' already exists ; I already have the users table in there

**Comment by duysolo** [comment]
It's because of WebEd use that table to store admin users.
You can rename the current `users` table to other name.

**Comment by goodman77** [comment]
the issue is I have another Laravel Package that uses "user" table if I rename it , then it will messup that package

**Comment by duysolo** [comment]
I think in next version, I will rename all tables with `we_` prefix.

**Comment by bhazboun123** [comment]
yes that would be a good idea :) so for now can I rename it?

**Comment by bhazboun123** [comment]
let me try renaming and see if it works

**Comment by duysolo** [comment]
Ok, you can try.

**Comment by bhazboun123** [comment]
Now I am getting error with : Base table or view already exists: 1050 Table 'password_resets' already exists, I don't know seems not ganna work

**Comment by duysolo** [comment]
lol
So many tables conflict in the existing database. It's so hard to use WebEd with an existing project.
I will rename all tables asap.

**Comment by goodman77** [comment]
How long it will take you to rename it, I need to install it asap as I need to give this a try to see if I can use it or not

**Comment by duysolo** [comment]
Within this week, everything will be done.

**Comment by goodman77** [comment]
great send me a message as soon as you can

**Comment by goodman77** [comment]
I got it to work now :) I had to rename user and password_reset tables and run the installation, but I think once you have added the prefix this will fix this issue

**Comment by duysolo** [comment]
It's a good news.

**Comment by goodman77** [comment]
Question: so I created a page and I made slug / , and it still showing the Laravel page? do you know why is that?
