### ISSUE TITLE
Error with Call to undefined function WebEd\Themes\Triangle\Http\Controllers\google_recaptcha()

### ISSUE THREAD

**Issue by goodman77** [sgsoft-studio/webed#30]
I have managed to install the cms successfuly

I logged in and created a page with slug "/test" , when I go and view this page I am getting this error:

Call to undefined function WebEd\Themes\Triangle\Http\Controllers\google_recaptcha()

I have Activated and Installed the default theme

**Comment by duysolo** [comment]
I see.
Please run these command:
```
composer update
php artisan vendor:publish --provider=WebEd\Base\Providers\ModuleProvider --tag=webed-assets --force
```

**Comment by goodman77** [comment]
Now I am getting these errors : Undefined variable: testimonials (View: themes/triangle/resources/views/front/_partials/footer.blade.php) (View: themes/triangle/resources/views/front/_partials/footer.blade.php) (View: themes/triangle/resources/views/front/_partials/footer.blade.php)

**Comment by duysolo** [comment]
You need to use the database from sample data.

**Comment by goodman77** [comment]
is the in the admin area?

**Comment by duysolo** [comment]
No, import it from phpmyadmin. 
I'm fixing the default theme.

**Comment by goodman77** [comment]
what to import from phpmyadmin? what is the table name?

**Comment by duysolo** [comment]
You can follow the instructions in `readme.md` of triangle theme.
Please ignore the config.

**Comment by goodman77** [comment]
I am trying to install the capatcha , and when I click on install , I am getting a log error

I check laravel error and it is :  local.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: Command "module:install" is not defined.

Maybe something you need to update as well?

**Comment by goodman77** [comment]
I did mysql dump with sample data and now its working but installing capatcha give me an error

**Comment by duysolo** [comment]
I fixed the install command.

**Comment by goodman77** [comment]
How about changing tables prefix ?

**Comment by duysolo** [comment]
It's so hard, because so many people use this cms now. 
I'm thinking about that and let you know soon.
