### ISSUE TITLE
Short code doesnt work?

### ISSUE THREAD

**Issue by goodman77** [sgsoft-studio/webed#31]
I created a static block code and it generate a shortcode like this  
[static_block alias="one"]

but when I add this to my test page , nothing shows up?

any idea

**Comment by sangnguyenplus** [comment]
Hi @goodman77,
You can test static block here http://cms.botble.com/admin/block.
Actually, static block on Botble CMS is the same with Webed =))

**Comment by goodman77** [comment]
That is not my point , I am saying it's not working on my end how do you make it work??

**Comment by sangnguyenplus** [comment]
Just a joke, you can find why it does not work then create a pull request for it. 
I think the author of Webed is so busy now. :dancer:

**Comment by duysolo** [comment]
Could you show me some picture? 
About the shortcode, there are 2 ways to use it
- Paste it in page content.
- Run directly from view via `do_shortcode('[static_block alias="one"]')`.

**Comment by goodman77** [comment]
Hi I post it in a page , so it should work right ? But it's not displaying any content

**Comment by duysolo** [comment]
First you need to create a static block, then place any content in that static block.
And what page template you set for that page? Some page template does not show the content, so the shortcode does not work.

**Comment by goodman77** [comment]
When I create the static block what should the page template be ?

**Comment by duysolo** [comment]
Sorry, it based on the theme you use.
For example in `triangle` theme, it can be blank template.

**Comment by goodman77** [comment]
I will check it out

**Comment by ghost** [comment]
@sangnguyenplus the F is wrong with you
