### ISSUE TITLE
Changing users table with prefix?

### ISSUE THREAD

**Issue by bhazboun123** [sgsoft-studio/webed#32]
I am getting an error with installation since the users table exists with initial laravel installation

my question , how do I change ALL tables that Webed cms is using to start with a prefix like cms_*

can you please help

Thanks

**Comment by duysolo** [comment]
To install WebEd, please use command
```
composer create-project sgsoft-studio/webed webed
```
It does not contain default migration of Laravel.

**Comment by bhazboun123** [comment]
I already installed webed in an existing Laravel project, I just need to modify the tables prefix in the code for "users" and "password_reset" tables , can I do that?

**Comment by duysolo** [comment]
Currently I do not support that feature.
It's put on backlog already. I will implement it soon.

**Comment by bhazboun123** [comment]
can you just point me to which files I need to modify so I can make this happen?

**Comment by duysolo** [comment]
You can run this command:
```
php artisan core:export webed-users
composer dump-autoload
```
Now, module `Users` will appear at `core/users` folder. You can edit them.

**Comment by bhazboun123** [comment]
Great Thanks I will give it a try
