### ISSUE TITLE
After installation ElFinder don't work

### ISSUE THREAD

**Issue by trippo** [sgsoft-studio/webed#34]
I tried to make work ElFinder without success...
I give to uploads folder all permissions but elfinder alway stuck on this screen:
![schermata 2017-06-30 alle 10 44 02](https://user-images.githubusercontent.com/497169/27728073-38ac9004-5d81-11e7-994e-e8199875803b.jpg)

**Comment by duysolo** [comment]
Hello,

Could you show me the error message that you received?

**Comment by trippo** [comment]
The connector method was stationary to pending

**Comment by duysolo** [comment]
I never have heard about that error.

Which operating system that you use?

**Comment by trippo** [comment]
Mac os X last version, php 7.1.1

**Comment by duysolo** [comment]
I'm the same, but everything still fine :)
How can I catch the case you have?

**Comment by trippo** [comment]
i can show you... i added you on skype please accept

**Comment by duysolo** [comment]
I added.
