### ISSUE TITLE
Frontend as module

### ISSUE THREAD

**Issue by lukacavic** [sgsoft-studio/webed#35]
Hi, a good feature would be to enable/disable frontend in settings, or make it as module/plugin? 

You could use Webed as base for CRM, not only CMS?

Thanks

**Comment by duysolo** [comment]
Hello,

Of course, you can create more features to make it work as CRM. The best way to do that is create a plugin.

About the frontend settings, I think we dont need to do that. 

You can overwrite the **webed-pages** config to change the route to match your business. Or do that from a plugin, etc.

If you dont wanna create a plugin, you can use the default app folder of Laravel. WebEd is just a package.

In next version, I will change all table name, so we can use WebEd in an existing project.

**Comment by lukacavic** [comment]
Thanks for response. 

Where can I see all avaliable filters and actions in app? 

Can pages module be disabled? 

And how can I make saas implementation of app, so each table has company_id column? To rum multiple companies on single db? Is it possible to do that using plugin? 

Thanks

**Comment by duysolo** [comment]
Hello,

The **pages** module is a core module, so it cannot be disabled. But you can try to remove it from dashboard menu.
