### ISSUE TITLE
Menu section

### ISSUE THREAD

**Issue by reshnk** [sgsoft-studio/webed#37]
I'm editing mainmenu and in my design i got a class for the ul section ul class="navigation clearfix" 
like this..
 &lt;ul class="navigation clearfix"&gt;
                              
&lt;/ul&gt;

But i don't see an option for giving class for &lt;ul&gt;, I see css options for the &lt;li&gt;in the custom link section
Help, I'm a beginner

**Comment by duysolo** [comment]
Hello,

You can modify it in the theme. See code in `AbstractController` of your theme.
