### ISSUE TITLE
Undefined variable: testimonials

### ISSUE THREAD

**Issue by bijondev** [sgsoft-studio/webed#38]
I just flow your instuction. But Its showing dlowing error

Undefined variable: testimonials (View: C:\xampp\htdocs\webed\themes\triangle\resources\views\front\_partials\footer.blade.php) (View: C:\xampp\htdocs\webed\themes\triangle\resources\views\front\_partials\footer.blade.php) (View: C:\xampp\htdocs\webed\themes\triangle\resources\views\front\_partials\footer.blade.php)
--
in 1af65b77165779398483e62c0322c83f81f25bd3.php (line 9)

**Comment by duysolo** [comment]
https://github.com/sgsoft-studio/webed/issues/42
