### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by nikhil167** [sgsoft-studio/webed#39]
I created 2 new menus named 'main menu' and 'top menu'. My question is how i call it on 'header.blade.php' The default code shows  {!! $cmsMenuHtml !!}.
How i change it according to my menu names?
Help, Thanks

**Comment by duysolo** [comment]
You can see the code in method `getMenu` of `AbstractController` from your theme.

**Comment by nikhil167** [comment]
While installing plugins this -->

"The base module of this class is enabled, but class not found: WebEd\Plugins\Blog\Providers\ModuleProvider. Please review and add the namespace of this module to composer autoload section, then run composer dump-autoload"

"The base module of this class is enabled, but class not found: WebEd\Plugins\Captcha\Providers\ModuleProvider. Please review and add the namespace of this module to composer autoload section, then run composer dump-autoload"

![14](https://user-images.githubusercontent.com/26650913/28557344-7c91c3a0-7129-11e7-871f-d1d58504f1e8.jpg)

Can you help me with step by step..
Thanks

**Comment by duysolo** [comment]
Hello,

From your terminal, run this command:
```
composer dump-autoload
```

**Comment by nikhil167** [comment]
Hi, Thanks for the reply,

Ya i have tried that no change :(

**Comment by duysolo** [comment]
Hmm,

Try to disable and enable these plugins again.

**Comment by nikhil167** [comment]
I tried that too-------->
![15](https://user-images.githubusercontent.com/26650913/28562721-0f5503d4-7141-11e7-87f8-56a419bebe45.jpg)

![16](https://user-images.githubusercontent.com/26650913/28562827-6abae5ae-7141-11e7-9cfa-0ca2de685e27.jpg)

**Comment by nikhil167** [comment]
Hi, Looking forward for your reply,
Thanks

**Comment by duysolo** [comment]
Could you open `Network` tab of chrome debugger, then show me the error screen?

**Comment by nikhil167** [comment]
ok now the "composer dump-autoload" error is gone after updating composer and editing the json file
 "WebEd\\Plugins\\Blog\\":"plugins/blog/src" to  "WebEd\\Plugins\\Blog\\":"plugins/blog-3.1/src"

But still can't update and disable plugins
Here is the screenshot
![17](https://user-images.githubusercontent.com/26650913/28618887-ae3e02b0-7223-11e7-8dac-18c33fe4e346.jpg)

**Comment by duysolo** [comment]
![GitHub Logo](https://content.screencast.com/users/TedoziManson/folders/Jing/media/ae12e7b3-90da-46ca-b3af-a1136d604e94/00000034.png)
Something like this. If there are error, you can see the message.

**Comment by nikhil167** [comment]
![18](https://user-images.githubusercontent.com/26650913/28708882-7f4315e4-739b-11e7-933a-25196c03d4e7.jpg)

**Comment by duysolo** [comment]
Why your `plugins` table does not have field `updated_at`?

**Comment by nikhil167** [comment]
i don't know :( 
What am i supposed to do?

**Comment by duysolo** [comment]
Try to run `php artisan migrate` :D
