### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by minhnghiadev** [sgsoft-studio/webed#4]
Hi bro, 
I very interest this CMS. But i dont' know PHP. Can you have me install it on my computer?

**Comment by sangnguyenplus** [comment]
Hi @minhnghiadev,
This is stupid question. Please check document site here http://webed-docs.hitbui.com/docs/documentation.html
Thanks!

**Comment by cumez1** [comment]
How to install plugins

**Comment by sangnguyenplus** [comment]
He changed the issue's description :(

**Comment by duysolo** [comment]
Yes, the original title is "How to install it" lol
