### ISSUE TITLE
Bug Undefined variable: testimonials

### ISSUE THREAD

**Issue by tnvhung** [sgsoft-studio/webed#42]
![image](https://user-images.githubusercontent.com/7857148/29861916-1cec66de-8d95-11e7-8fbd-33ceb58b40df.png)
Website have issue after install. How to resolve this bug?

**Comment by duysolo** [comment]
Hello,

You can try to use the sample database, which put in  `plugins/themes/triangles/sample-data`

**Comment by mrabbani** [comment]
Go to `admincp/theme-options` url.  Select `Footer content page` and `Items per page`
