### ISSUE TITLE
Extending menuHtml

### ISSUE THREAD

**Issue by decryptedchaos** [sgsoft-studio/webed#43]
Firstly,  great project,  almost exactly what i was looking for, A basic bootstrap laravel cms which i can extend, I hope it continues to progress.  

I would suggest better documentation,  I've been over the documentation and it is very brief and only outlines the basics of how to get the system working. 

Not much in the way of troubleshooting or in-depth explanation of how routing is setup. 

Never mind my original issue i have solved it so i'm updating this issue with another question, while i realize this is not the best channel for support related questions there isn't really any website or forums. 

I'm trying to create a bootstrap megamenu in the triangle theme. 

What i've come up with so far is i need to extend the menuHtml class 

As seen below (modified) 

```
  protected function getMenu($type, $relatedId)
    {
        $menuHtml = $this->cacheService
            ->setCacheKey(__FUNCTION__, func_get_args())
            ->retrieveFromCache(function () use ($type, $relatedId) {
                return webed_render_menu(get_setting('main_menu', 'main-menu'), [
                    'id' => '',
                    'class' => 'nav navbar-nav navbar-right',
                    'container_class' => 'collapse navbar-collapse',
                    'has_sub_class' => 'dropdown megamenu-dropdown',
                    'container_tag' => 'nav',
                    'container_id' => '',
                    'group_tag' => 'ul',
                    'child_tag' => 'li',
                    'submenu_class' => 'dropdown-menu mega-dropdown-menu row',
                    'item_class' => '',
                    'active_class' => 'item active',
                    'menu_active' => [
                        'type' => $type,
                        'related_id' => $relatedId,
                    ]
                ]);
            });

        view()->share([
            'cmsMenuHtml' => $menuHtml
        ]);
        return $menuHtml;
    }
}
```
From what i can tell, i need another css class level 

one for main title  
one for dropdown-header  (Blank link which separates the sections of the megamenu) 
one for item   

Either i'm reading it wrong or the above block of code doesn't give enough css levels to make this work. 

Could someone here provide some insight on how extend this function.

**Comment by duysolo** [comment]
This is the default params of `webed_render_menu` function:

```
[
            'class' => 'nav nav-bar',
            'id' => '',
            'container_tag' => 'nav',
            'container_class' => '',
            'container_id' => '',
            'group_tag' => 'ul',
            'child_tag' => 'li',
            'has_sub_class' => 'has-children',
            'submenu_class' => 'sub-menu',
            'item_class' => '',
            'active_class' => 'active current-menu-item',
            'menu_active' => [
                'type' => 'custom-link',
                'entity_id' => null,
            ],
            'view' => 'webed-menus::front._renderer.menu',
        ]
```

You can specify your view :D

**Comment by decryptedchaos** [comment]
Thanks for your reply, i think i have narrowed down the problem (perhaps) getting the menu system to understand 3rd level menus seems to be the issue.  

As this would be the simple way to do it  group all 3rd level menus into their own `<ul> ` with a css class. 

I'm sure there is a way to make laravel check if it's the first child and create a `<ul>` foreach first child,  but at this point that's probably beyond my ability with laravel. 

I should note,  this should have also been possible (hackable?) via the admin/menu css class input box. 

However, it does not appear that second level menu items or above take the class input from the admincp, I'm not sure if this is a bug or intended. 

Perhaps an example would better illustrate the problem 

I'm making a menu simmular to this one 
https://bootsnipp.com/snippets/featured/bootstrap-mega-menu

If you inspect the code you will see that each column is separated into its own `<ul class="col-sm-3">` and then each first child inside of that `<ul>` is given the css class "dropdown-header"  

With the default menu code i don't see a way to implement these extra levels.

**Comment by duysolo** [comment]
Hello,

The mega menu will be supported as a static block. I will update this feature soon.
