### ISSUE TITLE
I have setup successfully with database

### ISSUE THREAD

**Issue by kd-s-t** [sgsoft-studio/webed#45]
The issue is Im seeing this plain text with white background: "You need to active a theme"

**Comment by duysolo** [comment]
Hello,

You must go to Dashboard --> Plugins. Active and install the default theme (NewsTV).

Btw, the NewsTV theme require plugin `blog`. 

Please go here to download plugins: [https://github.com/webed-plugins](https://github.com/webed-plugins). Only plugins that have released version match `4.0.*` can work with WebEd 4

**Comment by kenntinio** [comment]
When I logged in, I could not go through dashboard because its showing "You need to active a theme"

**Comment by kd-s-t** [comment]
@duyphan2502 
I login to http://cms.webed.local:8888/public/admincp/auth/login

Then redirects me to http://cms.webed.local:8888/public/admincp with "You need to active a theme"
