### ISSUE TITLE
About module alias

### ISSUE THREAD

**Issue by lilili001** [sgsoft-studio/webed#49]
view files within everymodule,where does the package alias name come from,like below , where is "webed-core" come from?

`@extends('webed-core::admin._master')`

**Comment by duysolo** [comment]
Hello,

Each module has a `ModuleProvider` that registered everything of the module. 
You can view that file at `src/Providers/ModuleProvider`

**Comment by lilili001** [comment]
I found it ,  thanks! 
By the way, I have another question, how the part themes and plugins work , 
can user install theme or plugin from somewhere , can developers develop a custom theme or one plugin by themeselves?  how?
