### ISSUE TITLE
Error after install :(

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#57]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'WebEd\Base\CustomFields\Facades\CustomFieldSupportFacade' not found

php 7.0  - 7.1  - 7.2

vendor/sgsoft-studio/pages/src/Providers/BootstrapModuleServiceProvider.php

CustomFieldSupportFacade::registerRule('basic', trans('webed-custom-fields::rules.page_template'), 'page_template', function () {

**Comment by CherishNA** [comment]
I have the same problem.

**Comment by duysolo** [comment]
Hello,

You can follow these steps:
1. Download the latest version of custom fields in `github/duyphan2502/custom-fields`
2. Extract the zip file at `/core/custom-fields`
3. Set autoload psr4 for the custom fields by modify the `composer.json`
4. Publish the core config, then add the custom fields's `ModuleProvider` to `config/webed-core`

**Comment by zhangyuxiao** [comment]
how Publish the core config ?  like this ?: php artisan core:vendor:publish webed-custom-fields??? notice me Module not exists

**Comment by lidianhao123** [comment]
@duyphan2502 I meet the same problem. How to "Publish the core config, then add the custom fields's ModuleProvider to config/webed-core".

**Comment by yuandonghua** [comment]
There is no config/webed-core here
