### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by gtnl** [sgsoft-studio/webed#59]
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'WebEd\Base\CustomFields\Facades\CustomFieldSupportFacade' not found

**Comment by rafayhingoro** [comment]
duplicate of and answered [here](https://github.com/sgsoft-studio/webed/issues/57#issuecomment-370630884)

**Comment by duysolo** [comment]
I fixed this issues.
