### ISSUE TITLE
where is the routes are defined?

### ISSUE THREAD

**Issue by aneeshsudhakaran** [sgsoft-studio/webed#6]
or implemented any other mechanism for routes?

**Comment by duysolo** [comment]
Which route do you wanna custom? For admin dashboard or front site?

**Comment by aneeshsudhakaran** [comment]
i mean the URLS like "admincp/pages", "admincp" etc
how this calling corresponding controller function.

see this 
`https://github.com/aneeshsudhakaran/laravel5.3demo/blob/master/routes/web.php`
here i defining the URL in routes for invoke controller.
In your project how pages are working without routes entries?

**Comment by duysolo** [comment]
Ah ok, you can view them in vendor/sgsoft-studio folder. The routes in admin cannot modified. You can just modify the prefix route **admincp** to other you want by modify .env **WEBED_ADMIN_ROUTE**.

**Comment by aneeshsudhakaran** [comment]
ok thx
