### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#7]
Hello, what is the minimum required version of php? Something I have not worked on PHP 5.6.27 - Internal Server Error :(  

Help me please.

**Comment by duysolo** [comment]
Could you take a screenshot? 
This is server requirement: [https://laravel.com/docs/5.4#server-requirements](https://laravel.com/docs/5.4#server-requirements)

**Comment by yuri25** [comment]
All figured out, the problem was in the file .htaccess directive Options -MultiViews. I comment out of her, and the problem is solved. Thank you very much for your responsiveness.

**Comment by duysolo** [comment]
Ok. Feel free to contact me :)
