### ISSUE TITLE
Problem plugins

### ISSUE THREAD

**Issue by yuri25** [sgsoft-studio/webed#9]
https://github.com/webed-themes/sedna#how-to-use

After the action template demo data problems begin with the activation, deactivation and installing plug-ins.
I get this error ..
Some error occurred. View console log for more information.
![error-1](https://cloud.githubusercontent.com/assets/253228/23086069/28d570dc-f57c-11e6-8447-8919a30febf2.jpg)

**Comment by duysolo** [comment]
Hello,

It's because of the sample data. I've updated the sample data, you can try it.

**Comment by yuri25** [comment]
php artisan vendor:publish --tag=webed-public-assets

PHP Fatal error:  Class 'Laravel\Tinker\TinkerServiceProvider' not found in /......../ptznew.ru/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laravel\Tinker\TinkerServiceProvider' not found

I do as it is written here: https://github.com/webed-themes/sedna#how-to-use

**Comment by yuri25** [comment]
This problem was solved ....
After editing the home page menu does not work and disturbed the whole entire work site :(

Here's a look please  http://ptznew.ru

It is possible that once set the whole project together with all plugins and design theme .... without the "dancing with a tambourine"?
really liked the system, but quite difficult to configure all of the different sections ....

Thank.

**Comment by duysolo** [comment]
It's because of the Laravel Tinker package in Laravel 5.4. You can go through to ```config/app.php``` and command the line ```Laravel\Tinker\TinkerServiceProvider::class,```,
or you can try to run ```composer require laravel/tinker:~1.0```

Btw, i've updated the ```composer.json```.

**Comment by duysolo** [comment]
Yeah, I'm building a system to manage the packages. You can download the package from the dashboard.

**Comment by yuri25** [comment]
Well, this problem is also solved or will be solved .... :)
Now, when editing the page does not display blocks of content ... although previously displayed ... Now only this:

![image](https://cloud.githubusercontent.com/assets/253228/23094194/82cd2056-f605-11e6-8cb6-819f81f26d27.png)

![image](https://cloud.githubusercontent.com/assets/253228/23094199/916c75ee-f605-11e6-8cb8-93ce6806023f.png)

I'll try later to install all over again

**Comment by duysolo** [comment]
This theme is made for WebEd version 2. I changed some fields in backend.
With this case, you can go to **Custom Fields** and edit all the field groups. Set the **Page template** rule to **HomePage**
Or try to download the latest db I've pushed.

**Comment by yuri25** [comment]
Ok, Thank.

**Comment by duysolo** [comment]
Everything is ok now?

**Comment by yuri25** [comment]
No :( 
Whoops, looks like something went wrong.

2/2
ErrorException in 198823d5fa7d130c608a5f993d457b59ad6a350c.php line 110:
Invalid argument supplied for foreach() (View: /....../ptznew.ru/themes/sedna/resources/views/front/page-templates/homepage.blade.php)

What I edited it wrong :)

**Comment by yuri25** [comment]
The cache is cleared to no avail
please see here  http://ptznew.ru

**Comment by duysolo** [comment]
My email is **duyphan.developer@gmail.com**.  Could you send me the dashboard credentials?

**Comment by yuri25** [comment]
This is a test site, please:
admin
123456

**Comment by duysolo** [comment]
lol
You deleted the custom fields in the field group: **Homepage CMS blocks - Blog intro**.

**Comment by yuri25** [comment]
And what not? Maybe add a field again?

**Comment by duysolo** [comment]
Using custom fields is very convenient, but very dangerous too.

**Comment by yuri25** [comment]
Well ... I reinstalled

**Comment by yuri25** [comment]
Install the plugin blog ... Now when you try to view the recording issue is:
Class WebEd\Themes\Sedna\Http\Controllers\Blog\PostController not exists

Please excuse me if tired :)

**Comment by duysolo** [comment]
Sorry, that theme doesn't support blog. 
I will make a blank theme soon.
Or you can try to create a new one by run command: ```php artisan theme:create your-theme-alias```

**Comment by yuri25** [comment]
Well, I will follow the development of your project. You can close issue. Thank you very much.
